### ISSUE TITLE
textConnector.js is not bundled by default

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-text-field-flow#103]
The connector is added with `addJavaScript` and flow maven plugin doesn't pick it.

As a workaround it can be manually added to a fragment

**Comment by Legioth** [comment]
Considering that there is very limited functionality in `textConnector.js`, I wonder if it would be better to instead send the entire snippet on-demand using `executeJavaScript` instead of loading it as a separate file?
