### ISSUE TITLE
When using a binder on a vaadin-text-field the server-side component and the client-side component can get out of sync

### ISSUE THREAD

**Issue by brp-benjamin** [vaadin/vaadin-text-field-flow#104]
Given a required text field bound with a binder and some valid initial value the following steps will set the client in a state where it is out of sync with the server.

1. Remove all content from the text field
2. Blur
3. Enter the character 'a' in the text field and remove it again
4. Blur

This can be reproduced with the following code snippet:

```Java
model = new ViewModel("initial value");
b = new Binder<ViewModel>();

TextField textField = new TextField();
textField.addValueChangeListener(event -> message.setText(
        String.format("Text field value changed from '%s' to '%s'",
                event.getOldValue(), event.getValue())));

b.forField(textField).asRequired().bind(ViewModel::getValue, ViewModel::setValue);
b.setBean(model);
```

Observed:  Server side the content of the text field is 'a'
Expected: Server side the content of the text field is empty string 

Note: This does not happen with the vaadin-text-field if it does not use a binder. I.e. the following code does not have this bug:

```Java
TextField textField = new TextField();
textField.setRequired(true);
textField.addValueChangeListener(event -> message.setText(
        String.format("Text field value changed from '%s' to '%s'",
                event.getOldValue(), event.getValue())));
```

Therefore this might be an issue in the binder code, though I have not yet reproduced it for other components. See https://github.com/brp-benjamin/vaadin-text-field-flow for a full example (start the server and navigate to http://localhost:9998/vaadin-text-field).

**Comment by ZheSun88** [comment]
one thing reminds me is `vaadin-text-field-flow` has it own `connector.js` [https://github.com/vaadin/vaadin-text-field-flow/blob/master/src/main/resources/META-INF/resources/frontend/textConnector.js]

**Comment by denis-anisimov** [comment]
Important note: you should not blur once the character `a` is typed into the field. It should be removed without blur and blur should happen only after removal .
Otherwise everything works fine.

**Comment by denis-anisimov** [comment]
This behavior is somehow caused be the client side behavior.
When `'a'`  is typed and removed the client side sends two RPC `mSync` messages: 
- property `invalid` value update ( to `false`)
- property `value`  update to `'a'`.

`invalid` hasn't ever been changed to `true` so there shouldn't be update at all for it.
property `value` is already `''` so it's value shouldn't be `'a'`.

Both RPCs are weird.

Zhe is right: the only difference in case with binder and without is a connector which is intended to switch off the client side validation when binder is used ( actually binder does only one thing:  it calls `setRequiredIndicatorVisible` ).
Looks like this is the reason of the behavior.

**Comment by denis-anisimov** [comment]
Here is the reason of the behavior :
- binder adds a required validator since it is used 
- the client side doesn't send any updates unless the value is committed
- once the field is cleared the binder sets it `invalid`.
- when `'a'` is typed the `invalid` property value is updated
- the client side sends update to the server side which also contains the property `value` change
- normally it doesn't send it because the listener is attached via `addEventListener('change',...`
- since the value hasn't been committed in the scenario and in the end the value is the same as it was before (an empty) the empty value is not sent to the server
- as a result the server side contains an interim value (which shouldn't have been sent at all) and the client side has the final value.

**Comment by ilya-ershov** [comment]
Is this fixed in latest snapshot?

**Comment by denis-anisimov** [comment]
Yes, it's fixed at least there.
In fact the component is already released with this fix. At least the latest component version should contain the fix.
