### ISSUE TITLE
Some patterns not work

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-text-field-flow#105]
_From @adexerivera on September 5, 2018 12:22_

Hi everybody,

I'm trying to usage this code, but can not use dots or comas to add decimals

```
TextField percentage = new TextField();
percentage.setPattern("(^(100(?:\\.0{1,2})?))|(?!^0*$)(?!^0*\\.0*$)^\\d{1,2}(\\.\\d{1,2})?$");
percentage.setPreventInvalidInput(true);
```

some help please, thanks.

_Copied from original issue: vaadin/vaadin-text-field#256_

**Comment by ZheSun88** [comment]
did a quick test, the pattern set from the `setPattern()` method has been modified somehow to 
`(^(100(?:\.0{1,2})?))|(?!^0*$)(?!^0*\.0*$)^\d{1,2}(\.\d{1,2})?$` instead of 
`(^(100(?:\\.0{1,2})?))|(?!^0*$)(?!^0*\\.0*$)^\\d{1,2}(\\.\\d{1,2})?$`

**Comment by adexerivera** [comment]
In java, the problem is that I need to escape the backslash character in order to use it with string

**Comment by ZheSun88** [comment]
@adexerivera Actually, in this case, the pattern has been escaped correctly and it can do the validation. (i guess the regex is not very correct to validation what you want.)
but when it is used with `prevent-invalid-input`, for me i cannot input any value in this case. 

@tomivirkki i know you have tested with `pattern` attribute for the webcomponent, but have you tried together with the `prevent-invalid-input`?

**Comment by adexerivera** [comment]
@ZheSun88 i want to validate percentage values (1.00 .. 100.00), i think that expresion it's correct, and i test here, https://regex101.com. It happens the same to me, when it is used with prevent-invalid-input, i cannot input any value.

**Comment by ZheSun88** [comment]
@adexerivera thanks for this feedback. I will keep you informed

**Comment by ZheSun88** [comment]
Hi @adexerivera , i think the title of this issue is talking the wrong error. With the current pattern, it can work with the percentage values with dot (But not comma), you can test with the link you have provided there. 

The problem is more about after `setPreventInvalidInput(true)` that you cannot input any value. Am i correct? As if i am removing this setting, the component can work well.

**Comment by ZheSun88** [comment]
Hi @adexerivera 

regarding this issue, we don't think there are any bugs in it. As when you are setting `setPreventInvalidInput(true)` , it ensures,  the value in the input field,  at any point cannot contradict the pattern. In case, any number patterns which follows the dot or comma (ie, `3.` or `4,`) are not valid. That is why you cannot input them there. 

so in this case, this issue will be closed, as other parts just work correctly.
