### ISSUE TITLE
TextFieldVariant.LUMO_SMALL is not working as expected

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-text-field-flow#125]
Tested on Vaadin 12
When a TextField is next to another component as a Button, it doesn't behave well when using TextFieldVariant.LUMO_SMALL

Example (in the third pair, the TextField should be smaller than the button but they are the same size):

		Button button = new Button("Click Me");
		button.addThemeVariants(ButtonVariant.LUMO_SMALL);

		TextField field = new TextField();
		field.addThemeVariants(TextFieldVariant.LUMO_SMALL);
		field.setPlaceholder("Type Here");

		add(new HorizontalLayout(button, field));

		button = new Button("Click Me");
		button.addThemeVariants(ButtonVariant.LUMO_SMALL);

		field = new TextField();
		field.setPlaceholder("Type Here");

		add(new HorizontalLayout(button, field));

		button = new Button("Click Me");

		field = new TextField();
		field.addThemeVariants(TextFieldVariant.LUMO_SMALL);
		field.setPlaceholder("Type Here");

		add(new HorizontalLayout(button, field));

**Comment by denis-anisimov** [comment]
I'm not sure whether this is a bug in text field or Horizontal layout.

But anyway. I can reproduce it with  platform `12.0-SNAPSHOT` .

**Comment by web-padawan** [comment]
Closing as a duplicate. There is now also #230 which also provides a screenshot confirming this.
