### ISSUE TITLE
Pattern

### ISSUE THREAD

**Issue by alabotski** [vaadin/vaadin-text-field-flow#140]
I create TextField
```
    private final TextField minAmountCash;
...
        minAmountCash = new TextField();
        minAmountCash.setPattern("\\d+(,\\d{2})?");
        minAmountCash.setPreventInvalidInput(true);
```

I try different patterns from here http://html5pattern.com/Miscs
But I can't enter double number =(
I can't enter "." symbol only numbers...

<img width="895" alt="image" src="https://user-images.githubusercontent.com/439337/52410207-93561580-2acf-11e9-948b-7c2894126957.png">

**Comment by web-padawan** [comment]
Your pattern does not allow `.` character but allows `,` so you should update it accordingly.
There is nothing to fix on the web component side, as pattern is propagated to the native `input`.
See also https://html.spec.whatwg.org/multipage/input.html#attr-input-pattern
