### ISSUE TITLE
TextField#setPreventInvalidInput(true) does not work when turning on the required indicator

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-text-field-flow#142]
@duy-ng-12354 commented on [Sat Nov 24 2018](https://github.com/vaadin/flow/issues/4814)

Hi,

I am trying to prevent invalid input from end-user by using the example in https://vaadin.com/components/vaadin-text-field/java-examples. It works well if I implement my text field the same as in the example. However, when I call the method TextField#setRequiredIndicatorVisible(true), the input restriction does not work anymore.

**Working codes:**
```
TextField dollarField = new TextField("Dollars");
dollarField.setPattern("[0-9]*");
dollarField.setPreventInvalidInput(true);
```

**Non-working codes:**
```
TextField dollarField = new TextField("Dollars");
dollarField.setPattern("[0-9]*");
dollarField.setPreventInvalidInput(true);
dollarField.setRequiredIndicatorVisible(true); // looks like it causes the issue
```

In addition, when I use the **Binder#asRequired(...)**, the method **setPreventInvalidInput** also does not work.
```
binder.forField(dollarField).asRequired("Cannot be blank")...
```
However, when I use another kind of validator, the input restriction works as expected
```
binder.forField(dollarField)
                .withValidator(value -> StringUtils.isNotBlank(value), "Cannot be blank")...
```

I am using vaadin 11.0.2.

Please help to take a look.

---

@mehdi-vaadin commented on [Tue Nov 27 2018](https://github.com/vaadin/flow/issues/4814#issuecomment-442049402)

This bug exists in Vaadin 12 as well.

**Comment by marcelo107** [comment]
Just ran into this. Can confirm this also exists in Vaadin 13.0.0.beta1. Any time frame on when this might be fixed?

**Comment by ovtep** [comment]
Me too ran into this. Also in 13 release...

**Comment by berndklb** [comment]
Hi @denis-anisimov 
It looks like that everything (setRequiredIndicatorVisible or Binder#asRequired(...)) is calling RequiredValidationUtil.updateClientValidation(requiredIndicatorVisible,this); and here the client validation will be disabled by:
execJS(component, "window.Vaadin.Flow.textConnector.disableClientValidation($0);");
I would assume that the pattern is a client validation. So maybe someone knows, why the client validation will be disabled if the field is required?

**Comment by denis-anisimov** [comment]
> Hi @denis-anisimov
> It looks like that everything (setRequiredIndicatorVisible or Binder#asRequired(...)) is calling RequiredValidationUtil.updateClientValidation(requiredIndicatorVisible,this); and here the client validation will be disabled by:
> execJS(component, "window.Vaadin.Flow.textConnector.disableClientValidation($0);");
> I would assume that the pattern is a client validation. So maybe someone knows, why the client validation will be disabled if the field is required?

Hi.
Yes, I know why it is.
There are many reasons for that.

The very first reason is javadoc for the method:
https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L224

It says that this method should be used with the `Binder`  only.
There is a separate `setRequired`  method which should be used if you don't need to disable clients side validation.

And `Binder` is the other reason why it disables the client side validation: it does the server side validation which is not compatible with the client side validation. The issue https://github.com/vaadin/flow/issues/4077 is caused by the enabled client side validation.
