### ISSUE TITLE
Feature request - Placeholder visible while typing

### ISSUE THREAD

**Issue by masbaehr** [vaadin/vaadin-text-field-flow#146]
I was looking for a way to keep the placeholder visible so the user knows how to input something, as typing will remove any hint:

Example:
![image](https://user-images.githubusercontent.com/38694044/53236930-bcf96a00-3695-11e9-8a87-3424629ab7bf.png)

**Comment by OlliTietavainenVaadin** [comment]
Also known as "masked input"

**Comment by web-padawan** [comment]
Closing as duplicate of vaadin/vaadin-text-field#408 which is a feature request for masked input.
