### ISSUE TITLE
TextArea: setting "max-height" via styles breaks rendering

### ISSUE THREAD

**Issue by anasmi** [vaadin/vaadin-text-field-flow#149]
Code to reproduce:
```
@Theme(value= Material.class,variant = Material.DARK)
////////
        TextArea area=new TextArea("Testing tex-area");
        area.getStyle().set("max-height","55px");
```
![textarea](https://user-images.githubusercontent.com/15248706/53392148-31d3e900-39a1-11e9-9fb7-dc82ce8e65a6.gif)

The workaround is to set max-height via styles for **value** part:
```
<!-- Define a theme module (in index.html or in a separate HTML import) -->
<dom-module id="textarea-atyle" theme-for="vaadin-text-area">
    <template>
        <style>
            /* Styles which will be included in my-element local scope */
            [part="value"] {
                max-height: 55px;
            }
        </style>
    </template>
</dom-module>
```

**Comment by anasmi** [comment]
Maybe it's _expecatable_, as styles applied to the `<vaadin-text-area>`, but it would be nice to have a documentation about TextArea and how to style it with an example. (haven't found one)

**Comment by web-padawan** [comment]
Looks like a duplicate of vaadin/vaadin-text-field#310

**Comment by anasmi** [comment]
@web-padawan based on the description, indeed looks like duplicate. Thanks for pointing out :) I will close this issue then, as it looks like there is a pull request to address the referenced one.
