### ISSUE TITLE
TextField setAutocapitalize doesn't work on Linux Ubuntu

### ISSUE THREAD

**Issue by BarneyIt** [vaadin/vaadin-text-field-flow#158]
Just For Your Info
Tested using Vaadin 13.0.1 and Chrome on Linux Ubuntu 16.
Code to reproduce the problem
`    	TextField textField = new TextField();
    	textField.setAutocapitalize(Autocapitalize.CHARACTERS);
    	Button button = new Button("Push me", e -> {
    		Notification.show(textField.getValue());
    	});
    	add(textField, button);`

**Comment by ZheSun88** [comment]
Hi,

Thanks for reporting this. 

From MDN, you can see:

>The `autocapitalize` attribute doesn’t affect behavior when typing on a physical keyboard. Instead, it affects the behavior of other input mechanisms, such as virtual keyboards on mobile devices and voice input.

-reference https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize

and i have tested with Chrome and safari on an IPhone, it works correctly. 
What we can do to make it more clear is adding more javadocs on this feature, that is why i didn't close this ticket.

**Comment by BarneyIt** [comment]
Sorry, Haven't understood that peculiar behaviour ... to me is Closeable.
Thanks

Il giorno mer 20 mar 2019 alle ore 13:15 Sun Zhe <notifications@github.com>
ha scritto:
