### ISSUE TITLE
NumberField setPattern and setPreventInvalidInput not working at all

### ISSUE THREAD

**Issue by ssindelar** [vaadin/vaadin-text-field-flow#167]
When creating a number field it is not possible to prevent invalid input.

NumberField number = new NumberField();
number.setPattern("[0-9]+");
number.setPreventInvalidInput(true);

It's similar to #142 but also happens when the field is not set as required. It didn't find any way to make it work.

**Comment by pekam** [comment]
`NumberField` should not have these APIs at all. There's a ticket #181 and open PR #240 for deprecating them.

We have created a new component, `IntegerField`, which will be included in Vaadin 14.1.
It prevents the user from entering anything but `[\d-+]` so it should fit your use case.
