### ISSUE TITLE
setInvalid(true) doesn't work in addValueChangeListener

### ISSUE THREAD

**Issue by sandronm** [vaadin/vaadin-text-field-flow#168]
Hello!

I have a TextField who needs to trigger a validation each time his value changed.

Here a simplify version of my code:

`
		setSynchronizedEvent(
				ValueChangeMode.eventForMode(ValueChangeMode.ON_BLUR, "value-changed"));

		setErrorMessage("Invalid date!");

		this.addValueChangeListener(event -> {
			String value = event.getValue();
			if (value != null && !value.startsWith("a")) {
				setInvalid(true);
				focus();
				return;
			}
		});
`

Then normally, if the user doesn't start with "a", the input must be invalid... but it doesn't work!
If I replaced setInvalid(true) by .setEnabled(false);, my textfield will be correctly disabled!

PS: I know, for this case, I may use the setPattern() but for my real case it's not possible, I need to make a validation inside addValueChangeListener().

**Comment by ZheSun88** [comment]
Hi, Thanks for reporting this issue. May i know which version of the platform/components that you are using?

**Comment by sandronm** [comment]
> Hi, Thanks for reporting this issue. May i know which version of the platform/components that you are using?

I'm using Vaadin 13.0.2.
I found a workaround to my need via the CustomField but this bug is still relevant I guess ;-)

**Comment by ZheSun88** [comment]
I am not sure that i understand you correctly or not. You have mentioned 
>If I replaced setInvalid(true) by setDisabled(true);, my textfield will be correctly disabled!

but i don't think textField has an API, `setDisabled`.

**Comment by sandronm** [comment]
> I am not sure that i understand you correctly or not. You have mentioned
> 
> > If I replaced setInvalid(true) by setDisabled(true);, my textfield will be correctly disabled!
> 
> but i don't think textField has an API, `setDisabled`.

Yes, sorry, it's setEnabled(false);
I edit my message

**Comment by ZheSun88** [comment]
Okay, If i understand correctly, you use case is preventing the user from typing anything which does not start with `a`, right ?

In this case, according to the definition for API `setInvalid()` -> 
``` 
Sets the textfield to show as invalid state and display error message.
```
This API doesn't prevent anything, it just shows the user that the validation failed. 
It looks we are missing the javadoc for this API, so do you think it will help you a bit if we add the javadoc to make it more clear?

**Comment by sandronm** [comment]
No I don't want to prevent anything.
I just want to warn my user that the value is incorrect and displaying an error message... just like setInvalid(true) is made for :-)

And like I said, this use case is not the real one, just a basic one to simplify the debugging ;-)

**Comment by sandronm** [comment]
The bug is: inside the lambda method of addValueChangeListener, it's impossible to set the field as invalid.
On the server side, the field is really invalid (isInvalid() returns true) but the change is not reflected to the client (the field has no red background and the error message is not visible)

**Comment by ZheSun88** [comment]
I have tried the following code on platform 13.0.3(released this morning)
```java
public class MainView extends VerticalLayout {

    public MainView() {
        TextField textField = new TextField();

        textField.setValueChangeMode(ValueChangeMode.ON_BLUR);
        textField.setErrorMessage("error");
        textField.addValueChangeListener(event -> {
            String value = event.getValue();
             if (value != null && !value.startsWith("a")) {
                 textField.setInvalid(true);
                 textField.focus();
                 return;
             }
        });

        add(textField);
    }
}

```

you can see the behavior below:
![textfield](https://user-images.githubusercontent.com/31067185/55387155-96064180-5539-11e9-8c5e-4c6fa2c951cc.gif)

**Comment by sandronm** [comment]
I tried your example with 13.0.2 and it also works.
Well... I don't know what I have done yesterday (I deleted my code because I found a better alternative to my need with CustomField)...

Probably my body is in need of caffeine... ;-)

Really sorry to take your time for nothing :x

**Comment by ZheSun88** [comment]
no problem, come back and open an issue when you have new finds at any time.
