### ISSUE TITLE
NumberField: Using setMaxLength has no effect on maximum number of allowed characters

### ISSUE THREAD

**Issue by JohannesLaidler** [vaadin/vaadin-text-field-flow#170]
### Description
Using `setMaxLength` on a `NumberField` has no effect on maximum number of allowed characters.

### Expected outcome
`NumberField` should prevent user input from exceeding the defined max-length amount.

### Actual outcome
User input can exceed defined max-length
```
NumberField numberField = new NumberField("NumberField");
numberField.setMaxLength(4);
```
![number-field-max-length-4](https://user-images.githubusercontent.com/45820614/55738726-f9a3d980-5a27-11e9-9d5a-5e671ce660c8.png)

### Example 
```
@Route("test")
public class VaadinTest extends VerticalLayout {

    public VaadinTest() {
        NumberField numberField = new NumberField("(max-length = 4)");
        numberField.setMaxLength(4);

        add(numberField);
    }
}
```

### Versions
- Vaadin / Flow version 13.0.1
- Java version jdk-11.0.2
- OS version Windows 10
- Browser version Google Chrome Version 73.0.3683.103 (64-Bit) / Mozilla Quantum 66.0.2 (64-Bit)

**Comment by ZheSun88** [comment]
Hi @JohannesLaidler , Thanks for reporting this. 

As this API is calling `getElement().setProperty("maxlength", maxlength);` directly. I will move this issue to the webcomponent repo.

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-text-field #356](https://github.com/vaadin/vaadin-text-field/issues/356) via [**ZenHub**](https://www.zenhub.com/)
