### ISSUE TITLE
Default width of NumberField is different from TextField default width

### ISSUE THREAD

**Issue by JohannesLaidler** [vaadin/vaadin-text-field-flow#171]
### Description
Default width of `NumberField` is different from `TextField` default width

### Expected outcome
Width of `NumberField` should be the same as `TextField` width, if no width is explicitly set.

### Actual outcome
![different-width](https://user-images.githubusercontent.com/45820614/55739706-ded26480-5a29-11e9-9fd4-6cc4ca4cff0d.png)

### Example 
```
@Route("test")
public class VaadinTest extends VerticalLayout {

    public VaadinTest() {
        add(new NumberField("NumberField"), new TextField("TextField"));
    }
}
```

### Versions
- Vaadin / Flow version 13.0.1
- Java version jdk-11.0.2
- OS version Windows 10
- Browser version Google Chrome Version 73.0.3683.103 (64-Bit)

**Comment by ZheSun88** [comment]
Issue moved to webcomponent repo

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-text-field #357](https://github.com/vaadin/vaadin-text-field/issues/357) via [**ZenHub**](https://www.zenhub.com/)
