### ISSUE TITLE
Deprecate setPattern and setPreventInvalidInput for NumberField

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-text-field-flow#181]
Native `<input type="number">` elements do not support use of the `pattern` attribute for making entered values conform to a specific regex pattern, so it should be deprecated for `NumberField` Flow.

**Comment by pekam** [comment]
Same applies to setters and getters for `minlength` and `maxlength`

**Comment by knoobie** [comment]
The deprecation of the methods doesn't stop the user from using this method - if this feature is **clearly not supported** an **UnsupportedOperationException** would be better and more clear for the developer.

**Comment by pekam** [comment]
@knoobie that's true. However, I don't think we can make that kind of a change for existing major versions. If this effectively no-op method is currently called somewhere, making it throw would break that application. From future major versions we can remove the method entirely.
