### ISSUE TITLE
setRequired method in NumberField should be public.

### ISSUE THREAD

**Issue by shadikhani** [vaadin/vaadin-text-field-flow#190]
We should have `setRequired` method in Number Field just like the Text Field declared as below:

    @Override
    public void setRequired(boolean required) {
        super.setRequired(required);
    }

Right now we cannot use setRequired for Number Fields.

**Comment by Legioth** [comment]
I think it goes the opposite way. `setRequired` should be removed from `TextField` as well. See https://github.com/vaadin/vaadin-text-field-flow/issues/134 for more details.
