### ISSUE TITLE
setRequiredIndicatorVisible does not work

### ISSUE THREAD

**Issue by shadikhani** [vaadin/vaadin-text-field-flow#191]
`setRequiredIndicatorVisible` works for neither the text-field nor the related components to the text-field like number-field and etc.

**Comment by Legioth** [comment]
My understanding is that `setRequiredIndicatorVisible` works exactly as is implied by the name: it makes the required indicator * visible. What it doesn't do is to also enable client-side required validation which would interfere with the server-side validation enabled using `asRequired` with `Binder`.
