### ISSUE TITLE
Implement TextArea

### ISSUE THREAD

**Issue by torok-peter** [vaadin/vaadin-text-field-flow#20]
Including
* unit tests
* demos similar to https://cdn.vaadin.com/vaadin-text-field/1.2.0-alpha1/demo/#text-area-demos
* IT tests
* readme file

**Comment by caalador** [comment]
Update demo content field to be a TextArea:
https://github.com/vaadin/flow-demo/blob/master/demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/BlogCreator.java

**Comment by denis-anisimov** [comment]
The demo cannot be updated at the moment because there is no version of text area component released (this awaits on its turn the Flow release). So there are 2 unsatisfied dependencies.
Once everything is released the demo can be updated.
I will extract it as another ticket.
