### ISSUE TITLE
TextField.setTitle() javadoc is incorrect

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-text-field-flow#207]
The current Javadoc in 14.0.0.rc3 says `Message to show to the user when validation fails.` however the function simply sets the `title="foo"` HTML attribute which is shown at all times, even if there is no apparent validation failure.
![Screenshot from 2019-07-05 10-52-35](https://user-images.githubusercontent.com/254091/60706956-4443cd80-9f13-11e9-8ebd-78aa6fdbce31.png)

**Comment by web-padawan** [comment]
Related to https://github.com/vaadin/vaadin-text-field/issues/293

**Comment by web-padawan** [comment]
This line should be updated to align with the updated JSDoc in the web component:
https://github.com/vaadin/vaadin-text-field-flow/blob/8c802842d35e281977ebffb170ff5c77a145b56a/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextField.java#L889
