### ISSUE TITLE
Make NumberField  PARSER and FORMATTER members that can be set

### ISSUE THREAD

**Issue by mkn1988** [vaadin/vaadin-text-field-flow#214]
Currently the *PARSER* and *FORMATTER* fields in **NumberField** are private static final.

```
    private static final SerializableFunction<String, Double> PARSER = valueFromClient -> valueFromClient == null
            || valueFromClient.isEmpty() ? null
                    : Double.parseDouble(valueFromClient);

    private static final SerializableFunction<Double, String> FORMATTER = valueFromModel -> valueFromModel == null
            ? ""
            : valueFromModel.toString();
```

In my usecase it would be desireable to be able to set those fields by myself to have control over the number-format used (e.g. *'100000000.0'* -> *'100,000,000.000000'* or *'1e8'*) and also over the locale of the formatting, since my business application supports multiple different languages that don't necessarily correspond with either browser or server locale.

**Comment by Legioth** [comment]
This is slightly more complex than just accessing the server-side instances since formatting and parsing is also being performed by the client-side implementation.

**Comment by mkn1988** [comment]
What would you suggest then? Currently I have a custom implementation extending GeneratedVaadinTextField which uses the standard constructor functionality with serializable functions for conversion, which works for now.
It would be nice though, to have the possibility embedded in the framework, so we do not have to rely on your internal constructors.

**Comment by web-padawan** [comment]
Closing in favor of #291 which is about NumberField and BigDecimalField. See also https://github.com/vaadin/vaadin-text-field-flow/issues/291#issuecomment-635915353
