### ISSUE TITLE
assertFocusShortcut is failing in SNAPSHOT 1.3 build

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/vaadin-text-field-flow#215]
See [TeamCity build log](https://bender.vaadin.com/viewLog.html?buildId=78907&buildTypeId=Flow_ComponentSnapshotPlatformV13_TextField&tab=buildResultsDiv).

Maybe fixing `sendKeys` to be the same as the new version in the master branch fixes the test. See [`SendKeyHelper.sendKeys`](https://github.com/vaadin/vaadin-text-field-flow/blob/master/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/SendKeysHelper.java#L20).

**Comment by web-padawan** [comment]
This should not be the case now. Closing.
