### ISSUE TITLE
TextField with ThemeVariant.LUMO_SMALL is not aligned correctly

### ISSUE THREAD

**Issue by chhorz** [vaadin/vaadin-text-field-flow#230]
Hello together,

i am currently facing an issue with a Vaadin TextField and the small variant of the Lumo theme. As shown in the image below the text field in the middle has the small variant set. The button on the right side has also the small theme set.

But it seems, that the small text field has not the same bottom alignment as the other components:

![vaadin_textfield_finding](https://user-images.githubusercontent.com/16685526/66041537-5cc78200-e51a-11e9-8e65-d8dba559acce.png)

It seems to be related with the font-size of the has-label css part. If i uncheck the following style in the browser the components are all aligned on the same bottom level:

![vaadin_textfield_css](https://user-images.githubusercontent.com/16685526/66041844-2b9b8180-e51b-11e9-9d91-6ceefb798d0e.png)

If a create an TextField without an Label, the component is aligned the same way as the button.

Examle Code:
```java
TextField textFieldOne = new TextField("TextField 1");
TextField textFieldTwo = new TextField("TextField 2");
textFieldTwo.addThemeVariants(TextFieldVariant.LUMO_SMALL);

Button button = new Button("Button");
button.addThemeVariants(ButtonVariant.LUMO_SMALL);

HorizontalLayout inputLayout = new HorizontalLayout();
inputLayout.add(textFieldOne, textFieldTwo, button);
inputLayout.setVerticalComponentAlignment(FlexComponent.Alignment.END, textFieldTwo);
inputLayout.setVerticalComponentAlignment(FlexComponent.Alignment.END, button);
```

Vaadin-Version: 14.0.4

Regards,
Christian

**Comment by web-padawan** [comment]
Closing in favor of vaadin/vaadin-text-field#423 as the issue has to be fixed in that repository.
