### ISSUE TITLE
PasswordField not styled 

### ISSUE THREAD

**Issue by lucastanzani** [vaadin/vaadin-text-field-flow#234]
I just updated to Vaadin 14 **without** compatibility mode, and after a few tries I succeeded. But the only thing that I don't get right is the PasswordField:

![pwfield](https://user-images.githubusercontent.com/26148265/66207386-ec079d80-e6b2-11e9-9203-51bf136f4fe3.png)
![pwfieldvalue](https://user-images.githubusercontent.com/26148265/66207388-ec079d80-e6b2-11e9-882d-12c346bc6cd5.png)

This is what I get, and I tried previous versions but it didn't change.
This is seen by chrome, similar is in Firefox and other browsers. The field shows the content, and the reveal password button works.

Am I missing something?

**Comment by heruan** [comment]
See https://github.com/vaadin/vaadin-themable-mixin/issues/65 (fixed in [v1.5.1](https://github.com/vaadin/vaadin-themable-mixin/releases/tag/v1.5.1))

**Comment by web-padawan** [comment]
Closing as fixed. The above comment points to the correct issue and corresponding fix.
