### ISSUE TITLE
Character overlap in TextField in Firefox

### ISSUE THREAD

**Issue by ropoman** [vaadin/vaadin-text-field-flow#269]
![grafik](https://user-images.githubusercontent.com/6105301/69423763-47efb980-0d27-11ea-8ea1-8a5290769a74.png)

I am using Firefox 70.0.1 and often when I reach the end of the field and continue to type the characters overlap. A refresh or even klicking somewhere on the page solves it

**Comment by web-padawan** [comment]
This is already fixed by https://github.com/vaadin/vaadin-text-field/pull/436 so I'm closing this issue.
We will cherry-pick the fix to include it to 14.0.x patch release.
