### ISSUE TITLE
Don't accept setValue(null)

### ISSUE THREAD

**Issue by Legioth** [vaadin/vaadin-text-field-flow#28]
Right now, `textField.setValue(null)` and `textField.setValue("")` lead to exactly the same result both from the perspective of the user and for the return value of `getValue()`. This is confusing.

Suggested to instead make `TextField` work in the same way as in FW8, i.e. throwing an unchecked exception (currently not implemented in V10 and never returning `null` from `getValue()` (currently implemented in V10).

**Comment by SomeoneToIgnore** [comment]
Fixed in https://github.com/vaadin/vaadin-text-field-flow/pull/37
