### ISSUE TITLE
Add a demo for the TextField::setPattern API

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-text-field-flow#3]
@gilberto-torrezan commented on [Mon Sep 11 2017](https://github.com/vaadin/flow/issues/2362)

We don't have a demo showcasing how to use TextField::setPattern to create, for example, number-only fields.

---

@pleku commented on [Tue Sep 19 2017](https://github.com/vaadin/flow/issues/2362#issuecomment-330499591)

This demo could explicitly mention, is not supported with `Binder` currently, and is just a client side feature. (That is how it look currently for the newest `TextField`.

**Comment by enver-haase** [comment]
This problem materialized in the field - a customer did not know what to do, disliked V10+ for that reason.
I would like that.

**Comment by anasmi** [comment]
Some pattern examples are here
