### ISSUE TITLE
set Format on BigDecimalField

### ISSUE THREAD

**Issue by BayerPatrick** [vaadin/vaadin-text-field-flow#300]
We are using the `com.vaadin.flow.component.textfield.BigDecimalField` and want to set the format (e.g. the number of decimal places). Unfortunately we are missing some kind of `setFormat()` functionality.

**Comment by vaadin-miki** [comment]
as a workaround you could use a text field with regular expression and then parse the input

also, while the team is hard at work to make this feature as a part of the official release, feel free to use https://vaadin.com/directory/component/superfields - number fields in that add-on should fit your needs :)

disclaimer: I am the author of the addon that I linked

**Comment by web-padawan** [comment]
Closing in favor of #291
