### ISSUE TITLE
If minLength is set, isRequired should be set

### ISSUE THREAD

**Issue by jhult** [vaadin/vaadin-text-field-flow#323]
Logically, if `setMinLength(#)` is used and the value is greater than 0, then `setRequired(true)` should be automatically forced.

**Comment by rolfsmeds** [comment]
Not necessarily. A form could allow the field to be left blank, but have certain format requirements for the value if it is set.

**Comment by jhult** [comment]
I suppose that use-case does make sense.

Maybe we can leave this open for a bit to see if anyone else has thoughts. If no one else chimes in, we can leave as is and close it.

**Comment by jhult** [comment]
This functionality can be left as is.
