### ISSUE TITLE
IntegerField class gives null if you go outside the limits with wrong signs

### ISSUE THREAD

**Issue by DanielMartensson** [vaadin/vaadin-text-field-flow#330]
### Description of the bug
This is a issue with integer field class.

When I write -- (double minus) or +232 inside the integer field, then I will get null if the listener reads the value.
### Minimal reproducible example
```
                IntegerField do0Pulse = new IntegerField("Activated D0");
		do0Pulse.setMin(-100);
		do0Pulse.setMax(100);
		do0Pulse.setHasControls(true);
		do0Pulse.setValue(do0PulseSelected);
		do0Pulse.addValueChangeListener(e -> do0PulseSelected = e.getValue()); // Null here
```
Try to write e.g --101 or +232 and then you will get a null error. 
So why can I write + and --? Should not this integer field prevent me to write such things? 

### Expected behavior
It should not accept + or -- (double minus) as inputs. 
### Actual behavior
Gives null when I write -- (double minus) or +232.

### Versions:
    - Vaadin 14.2.1:
    - Java version: 11
    - OS version: Lubuntu Linux 20.04
    - Browser version (if applicable): Firefox
    - Application Server (if applicable): Spring Boot
    - IDE (if applicable): Eclipse IDE

**Comment by tomivirkki** [comment]
I guess the problem is with the type of `do0PulseSelected`. It doesn't show in the code snippet but it's probably of type `int` whereas it should be `Integer` so you can assign a `null` value to it (you'll get the same exception by just emptying the field).

> So why can I write + and --

The component uses `<input type="number">` internally which doesn't prevent you from typing such values. Instead it reports is as an empty string "" which `IntegerField` interprets as `null`.

**Comment by DanielMartensson** [comment]
> I guess the problem is with the type of `do0PulseSelected`. It doesn't show in the code snippet but it's probably of type `int` whereas it should be `Integer` so you can assign a `null` value to it (you'll get the same exception by just emptying the field).
> 
> > So why can I write + and --
> 
> The component uses `<input type="number">` internally which doesn't prevent you from typing such values. Instead it reports is as an empty string "" which `IntegerField` interprets as `null`.

Yes! `do0PulseSelected` is int in this case. So I have to use `Integer` instead or use an if-statement?

**Comment by tomivirkki** [comment]
> So I have to use Integer instead or use an if-statement?

Explicit check for `null` should also work 👍
