### ISSUE TITLE
TextField.getValue() always return an empty string

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-text-field-flow#4]
@mvysny commented on [Wed Oct 04 2017](https://github.com/vaadin/flow/issues/2591)

I have cloned the https://github.com/vaadin/skeleton-starter-flow project, ran `mvn jetty:run` on it and modified the `MainView`'s constructor to look like this:

```java
    public MainView() {
        ExampleTemplate template = new ExampleTemplate();

        final TextField foo = new TextField("Foo");
        Button button =  new Button("Click me", event -> template.setValue("Clicked! " + foo.getValue()));
        add(button, template, foo);
    }
```

When I click the "Click me" button, I want the text I've entered into the "Foo" field to appear along the "Clicked! " string. Instead, it comes up empty.

---

@mvysny commented on [Wed Oct 04 2017](https://github.com/vaadin/flow/issues/2591#issuecomment-334110235)

It's Flow 1.0.0.alpha3
![screenshot_20171004_130843](https://user-images.githubusercontent.com/254091/31170561-2bdc90e8-a905-11e7-8788-6eb426dd749a.png)

---

@ZheSun88 commented on [Wed Oct 04 2017](https://github.com/vaadin/flow/issues/2591#issuecomment-334164990)

In fact, you can use this way to achieve your goal:
```java
foo.addValueChangeListener(event -> event.getValue());
button.addClickListener(event -> {
     template.setValue("Clicked! " + foo.getValue());
});
```
If i recall correctly, in your way, the `foo.getValue()` is getting the initial value from the textField which is empty and it doesn't fire an event until you add a listener to it.. :)

![image](https://user-images.githubusercontent.com/31067185/31179795-9b11acf8-a925-11e7-9f62-c47b461987e1.png)

---

@mvysny commented on [Wed Oct 04 2017](https://github.com/vaadin/flow/issues/2591#issuecomment-334177368)

Ah, so the value is not transferred to the server side until the value change listener is added :) that's why it worked in the beverage demo - it uses binder which internally sets the value change listener.

Anyways, I believe that the value change listener should not be required in order for the value to be transferred from client to server.

---

@ZheSun88 commented on [Thu Oct 05 2017](https://github.com/vaadin/flow/issues/2591#issuecomment-334381498)

yes, the usage maybe look not very straightforward as using `getValue()` directly, but change listener is used to sync the value from the client to server.

---

@pleku commented on [Thu Oct 05 2017](https://github.com/vaadin/flow/issues/2591#issuecomment-334571024)

We should be making the `TextField` send the value to the server always on e.g. `blur` event when there has been a change, even if there is no `ValueChangeListener` applied.

Without that, we will confuse some users (like now), and that is always a bad thing. This is pretty similar what we had in FW 6 & 7 with the `immediate` property.

**Comment by tsuoanttila** [comment]
This is a major issue causing an ugly workaround in our booth demo. Fix ASAP.
