### ISSUE TITLE
TextField 'setList' method throws on client side

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-text-field-flow#5]
@tmattsso commented on [Wed Sep 20 2017](https://github.com/vaadin/flow/issues/2446)

in addition, it is undocumented on the server side, producing confusion in us poor developers.

---

@pleku commented on [Wed Sep 27 2017](https://github.com/vaadin/flow/issues/2446#issuecomment-332490736)

We should have an example of this in the component sample

**Comment by pleku** [comment]
It is not supported anymore. Please comment if you would need it
