### ISSUE TITLE
Setting the value using JS should synchronize to the server

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-text-field-flow#50]
Even if the value is synchronized to the server only when the user has completed inputting the value, i.e. on `blur`, the value should be synchronized directly if set using `element.value='foo';`

**Comment by pleku** [comment]
Why ? What use case ? What are you trying to achieve ?

**Comment by Artur-** [comment]
Currently, setting the value from a test so that the server knows about the change

**Comment by pleku** [comment]
This was apparently fixed in latest TB release ? https://github.com/vaadin/vaadin-components-testbench/releases/tag/1.0.0.alpha3

**Comment by Artur-** [comment]
I would call it worked around, but yes

**Comment by Artur-** [comment]
Remains to be seen how you can do latency compensation without this
