### ISSUE TITLE
Binder with StringToNumberConverter throws NullPointerException

### ISSUE THREAD

**Issue by brp-oskar** [vaadin/vaadin-text-field-flow#52]
When using the TextField component in a form with a `Binder` I would like to be able to bind a data object where the binded `Integer` value is null. That should be presented as an empty textfield.

At the moment this dosen't work due to the following:
* `AbstractStringToNumberConverter::convertToPresentation` returns `null` for a value that is null
* `TextField::setValue` throws NPE when providing a `null` value

I have copied the example code from https://vaadin.com/docs/v10/flow/binding-data/tutorial-flow-components-binder-validation.html#conversion into `TextFieldView.java` and it returns the following:

```
Caused by: java.lang.NullPointerException: value cannot be null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.vaadin.flow.component.textfield.TextField.setValue(TextField.java:179)
	at com.vaadin.flow.component.textfield.TextField.setValue(TextField.java:30)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.initFieldValue(Binder.java:1025)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.access$200(Binder.java:884)
	at com.vaadin.flow.data.binder.Binder.lambda$readBean$2(Binder.java:1540)
	at com.vaadin.flow.data.binder.Binder$$Lambda$180/1152863765.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.vaadin.flow.data.binder.Binder.readBean(Binder.java:1540)
```

This is the example code:

```java
class Data {
    Integer year;
}

private void addNumberFieldWithBinder() {
    // begin-source-example
    // source-example-heading: Number field with binder
    TextField yearOfBirthField = new TextField("Year of birth");

    Binder<Data> binder = new Binder<>();
    binder.forField(yearOfBirthField)
            .withConverter(new StringToIntegerConverter("Must enter a number"))
            .bind((bean) -> bean.year, (bean, year) -> bean.year = year);

    binder.readBean(new Data());
    // end-source-example

    addCard("Number field with binder", yearOfBirthField);
}
```

The issue https://github.com/vaadin/vaadin-text-field-flow/issues/28 has added the restriction of null value. Have you hade the converter in mind when adding this restriction?

**Comment by Legioth** [comment]
I think the current behaviour is in line with how things work with `Binder` in Framework 8 and it's also in line with how it's expected to work. 

When no converter is defined for a binding, `Binder` is automatically using `getEmptyValue()` for representing `null` values. When a converter is defined, it is expected that the developer wants full control over the values so this automatic conversion is disabled. You can explicitly define how `null` values should be handled by adding e.g. `withNullRepresentation("")`  before `withConverter`.

**Comment by brp-oskar** [comment]
Thanks. That works.
