### ISSUE TITLE
Support for an "on change" value change mode

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-text-field-flow#55]
After #44 the user can choose the value change mode for the fields, which are defined in the Flow's [`ValueChangeMode`](https://github.com/vaadin/flow/blob/063fb6eb249c50ade94fbf83ddff79a360ca17fd/flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java) enum, which provides two modes:

- `EAGER`: immediately fire to event to the server;
- `ON_BLUR`: fire the event when the input field loses focus.

None of these unfortunately provides the common behavior of the "on change" native event, which fires when the input change is "confirmed" i.e. blurred *or* the <kbd>ENTER</kbd> key is pressed.

Typical use case is filtering fields, the user types something and presses <kbd>ENTER</kbd> to search.

**Comment by Legioth** [comment]
Is there even any reason to preserve `ON_BLUR` if we introduce something like `ON_CHANGE`?

**Comment by heruan** [comment]
None from any use case I can imagine right now 🤔

**Comment by pleku** [comment]
This is a very trivial thing to do if we just change `blur` to `change`. Wondering if we should use `LAZY` and `EAGER` terminology on the server side or stick the the DOM names `CHANGE` and `INPUT`. The latter might force developers not familiar with the differences to get confused for a while and force them to think. The former should be always obvious (?).

**Comment by heruan** [comment]
I know that #33 and vaadin/flow#467 are not in the backlog for V10 (😭) but I'd choose a terminology which will fit well with a future `ValueChangeMode.DEBOUNCE`.
