### ISSUE TITLE
TextField.focus() doesn't actually focus the field, it just visually looks focused

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-text-field-flow#6]
@torok-peter commented on [Fri Sep 29 2017](https://github.com/vaadin/flow/issues/2548)

Originating from one of Jouni's PR comments in free-starter-flow @ https://github.com/vaadin/free-starter-flow/pull/98.

It may be a Flow bug, or a vaadin-text-field bug - further investigation is needed.

**Comment by asashour** [comment]
I am not able to reproduce, the TextField comes to `focus`, and typing keys works as expected.

**Comment by caalador** [comment]
Also couldn't reproduce. Focus worked as expected.
