### ISSUE TITLE
PasswordField is incompatible with TextField

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-text-field-flow#7]
@denis-anisimov commented on [Sat Sep 02 2017](https://github.com/vaadin/flow/issues/2306)

`PasswordField`  and `TextField` are two totally unrelated components.

But they have a lot of common methods (like `setPlaceholder` ).

Common methods have to be extracted to the separate common mixin which should be implemented by both of them.

---

@pleku commented on [Thu Sep 14 2017](https://github.com/vaadin/flow/issues/2306#issuecomment-329400240)

@SomeoneToIgnore, why did not `PasswordField` just extend `TextField` and add additional methods ?

---

@SomeoneToIgnore commented on [Thu Sep 14 2017](https://github.com/vaadin/flow/issues/2306#issuecomment-329401062)

This means that we won't be able to extend `GeneratedVaadinPasswordField` and will be needed to investigate that class after every update in order to copy-paste new changes.

If if is ok for you, we can go this way.

---

@SomeoneToIgnore commented on [Thu Sep 14 2017](https://github.com/vaadin/flow/issues/2306#issuecomment-329418038)

The analyzer is able to determine which JS class extends which already.
The generator is stateless now, but it can determine java class name from the javascript name, so it should rather straightforward to determine which java class should extend which.

---

@Legioth commented on [Thu Sep 14 2017](https://github.com/vaadin/flow/issues/2306#issuecomment-329434637)

Would it make sense to implement `PasswordField` as a hand-coded subclass of `TextField` instead of using the generator just for the sake of using the generator?

We should create components that make sense for the users. If there are cases that cannot be done with the current generator architecture, then we need to work around those limitations or rethink how the generator is used.

---

@SomeoneToIgnore commented on [Thu Sep 14 2017](https://github.com/vaadin/flow/issues/2306#issuecomment-329435927)

It would if you're ok with the fact that you need to manually check GeneratedPasswordField for changes each time you regenerate the build and copy the changes that are relevant.
One small extra concern is that after this change we will miss those annotations:
```java
@Generated({"Generator: com.vaadin.generator.ComponentGenerator#0.1-SNAPSHOT",
		"WebComponent: PasswordFieldElement#1.1.0-alpha4", "Flow#0.1-SNAPSHOT"})
@Tag("vaadin-password-field")
@HtmlImport("frontend://bower_components/vaadin-text-field/vaadin-password-field.html")
```
and will have the ones from TextField instead.

We will add those, obviously, but the other ones won't be gone: this is not good at least because of the extra import that we don't actually need.

---

@Legioth commented on [Thu Sep 14 2017](https://github.com/vaadin/flow/issues/2306#issuecomment-329442759)

Those are implementation details. The users care about whether they can use both components interchangeably. The best option is probably to have it the same way as in FW8, i.e. a shared `AbstractTextField` super class that contains everything that is common.

---

@SomeoneToIgnore commented on [Thu Sep 14 2017](https://github.com/vaadin/flow/issues/2306#issuecomment-329443604)

Those are implementation details that will lead to errors in components' behaviour since our dependencies are not fixed and that's why it's more proper to be done via generator.

As for the `AbstractTextField ` approach, sure, I believe, Dennis had meant the same in the description.

---

@Legioth commented on [Thu Sep 14 2017](https://github.com/vaadin/flow/issues/2306#issuecomment-329446445)

I don't see how this has anything to do with fixing dependencies.
* When dependency A changes, we might need to rerun the generator and verify that changes in the generated API are sensible.
* When dependency B changes, we might need to update some hand-written code.

In either case, the user needs a new version of a .jar file.

**Comment by asashour** [comment]
Now, `TextField`, `PasswordField` and `TextArea` do not share much, as each one has constructors and `getEmptyValue()`.

**Comment by pleku** [comment]
Could just extract the mixin interfaces to another interface and have common mixin interfaces and methods declared there.
