### ISSUE TITLE
Unable to retrieve text area value after running JavaScript (RC1)

### ISSUE THREAD

**Issue by vanquincy** [vaadin/vaadin-text-field-flow#81]
Hi,

previously in Vaadin Flow beta10 version, I was able to call textArea.getValue() after I set an element's `elementId.value = "abc";` when executing JavaScript. But after updating to version release candidate 1 (RC1), this method no longer works.

I have also tried `textArea.getElement().getAttribute("value");` also to no avail. Is there a work-around to this?

Below is a sample code to test the said issue:

**Java code:**
```
Button clickBttn = new Button("Click");
clickBttn.addClickListener(event -> page.executeJavaScript("test();"));

TextArea testTa = new TextArea("Test");
testTa.setId("test-ta");
            
Button testBttn = new Button("");
testBttn.setId("test-bttn");
testBttn.getElement().getStyle().set("visibility", "hidden");
testBttn.getElement().getStyle().set("height", "0");       
testBttn.addClickListener(e -> {
    System.out.println("TexT area value: " + testTa.getValue());
    System.out.println("TexT area attribute value: " + testTa.getElement().getAttribute("value"));
    System.out.println("TexT area textContent: " + testTa.getElement().getText());
    System.out.println("TexT area attribute textContent: " + testTa.getElement().getAttribute("textContent"));
});

add(testTa, testBttn, clickBttn);
```

**JavaScript code:**
```
var test = function() {
	var elementId = document.getElementById('test-ta');
	
	var complete_bttn = document.getElementById('test-bttn'); 
	elementId.value = 'abc';
	elementId.textContent = 'abc';
	
	complete_bttn.click();
	
};
```

Thanks.

**Comment by Legioth** [comment]
Might be related to https://github.com/vaadin/vaadin-text-field-flow/issues/73?

**Comment by Legioth** [comment]
You need to explicitly set the value change mode using `testTa.setValueChangeMode(ValueChangeMode.EAGER)` if you want it to send updates to the server in other situations than if the user blurs the field or presses [Enter] when it's focused. There was previously a bug that made the value always be sent even when using the default change mode of `ON_CHANGE`.
