### ISSUE TITLE
TextField Java demo is confusing

### ISSUE THREAD

**Issue by mikkoi-vaadin** [vaadin/vaadin-text-field-flow#93]
From Gitlab. B y Artur. 

https://gitlab.vaadin.com/vaadincom/webpage/issues/2808
--
https://vaadin.com/elements/vaadin-text-field/java-examples

Contains a generic text field followed by a text saying "Sync value on each change"

Entering a text in the field has no effect, if it does "sync value on each change" it does not show. What is a "change" anyway?

**Comment by ZheSun88** [comment]
the problem with this:  `Sync value on each change` is not a text, but a button. Currently, we are not using vaadin-components in the demos, so this is a nativebutton without theme. I can change the text of the button to make it more like a button, but not like a statement.
