### ISSUE TITLE
Vaadin Flow Text Field is not null safe

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-text-field-flow#94]
_From @ugurdoksan on July 27, 2018 15:3_

When I call textField.setValue( null ); it throws "Caused by: java.lang.NullPointerException: Null value is not supported". It is not usefull...

_Copied from original issue: vaadin/vaadin-core#191_

**Comment by web-padawan** [comment]
Thanks for the issue. This repo is for Web Components, and for their Java counterparts we have different repos. I will move it there so that our teammates could handle it appropriately.

**Comment by pekam** [comment]
It is useful to get an exception when the value that you're trying to set is `null`, because that might indicate that some part of your code is not working as expected.

There are no plans to change this default behavior.

If you want to clear the text-field, you should call `setValue("")`

**Comment by pleku** [comment]
This works as designed and works the same way as previously (V8). We don't consider `null` to be a correct value for an input field, thus the default value is an empty string `""`.

The javadocs could however be improved, to be similar as in V8:
```java
    /**
     * Sets the value of this text field. If the new value is not equal to
     * {@code getValue()}, fires a {@link ValueChangeEvent}. Throws
     * {@code NullPointerException} if the value is null.
     *
     * @param value
     *            the new value, not {@code null}
     * @throws NullPointerException
     *             if {@code value} is {@code null}
     */
    @Override
    public void setValue(String value) {
        Objects.requireNonNull(value, "value cannot be null");
        setValue(value, false);
    }
```

**Comment by Legioth** [comment]
One more thing to mention in this context is that `Binder` will take care of a crude default conversion of `null` when used with a `TextField`, as long as no converter is also defined.
